In [ ]:
# importing libraries
import pandas as pd
import numpy as np

In [ ]:
#load dataset
df=pd.read_csv('Road Transportation Accident  Dataset.csv')

In [ ]:
# display first 5 rows
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,01:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,01:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

In [ ]:
# display last rows
df.tail()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,Unknown,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

In [ ]:
# display particular rows
df.iloc[9:15]

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
9,17:20:00,Friday,18-30,Male,Junior high school,Employee,1-2yr,Automobile,Owner,2-5yrs,...,U-Turn,Passenger,Male,18-30,3,Driver,Normal,Not a Pedestrian,Moving Backward,Serious Injury
10,14:40:00,Saturday,18-30,Male,Above high school,Owner,1-2yr,Public (13?45 seats),Owner,Unknown,...,Turnover,na,na,na,na,NaN,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
11,14:40:00,Saturday,31-50,Male,Above high school,Employee,No Licence,Automobile,Owner,NaN,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Serious Injury
12,17:45:00,Thursday,18-30,Male,Junior high school,Employee,1-2yr,Public (> 45 seats),Owner,2-5yrs,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
13,17:45:00,Thursday,31-50,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,Above 10yr,...,Waiting to go,na,na,na,na,Other,Normal,Not a Pedestrian,No priority to vehicle,Slight Injury
14,17:45:00,Thursday,31-50,Male,Junior high school,Employee,Above 10yr,Automobile,Owner,1-2yr,...,Going straight,Driver or rider,Female,18-30,3,Driver,Normal,Not a Pedestrian,No distancing,Serious Injury

In [ ]:
# shape
df.shape

(12316, 32)

In [ ]:
# column names
df.columns

Index(['Time', 'Day_of_week', 'Age_band_of_driver', 'Sex_of_driver',
       'Educational_level', 'Vehicle_driver_relation', 'Driving_experience',
       'Type_of_vehicle', 'Owner_of_vehicle', 'Service_year_of_vehicle',
       'Defect_of_vehicle', 'Area_accident_occured', 'Lanes_or_Medians',
       'Road_allignment', 'Types_of_Junction', 'Road_surface_type',
       'Road_surface_conditions', 'Light_conditions', 'Weather_conditions',
       'Type_of_collision', 'Number_of_vehicles_involved',
       'Number_of_casualties', 'Vehicle_movement', 'Casualty_class',
       'Sex_of_casualty', 'Age_band_of_casualty', 'Casualty_severity',
       'Work_of_casuality', 'Fitness_of_casuality', 'Pedestrian_movement',
       'Cause_of_accident', 'Accident_severity'],
      dtype='object')

In [ ]:
# summary
df.describe()

       Number_of_vehicles_involved  Number_of_casualties
count                 12316.000000          12316.000000
mean                      2.040679              1.548149
std                       0.688790              1.007179
min                       1.000000              1.000000
25%                       2.000000              1.000000
50%                       2.000000              1.000000
75%                       2.000000              2.000000
max                       7.000000              8.000000

In [ ]:
# dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12174 non-null  object
 14  Types_of_Junction            11429 non-null  object
 15  Road_surface_type            12144 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12161 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            9118 non-null   object
 28  Fitness_of_casuality         9681 non-null   object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

In [ ]:
# display single column
df["Weather_conditions"]

0        Normal
1        Normal
2        Normal
3        Normal
4        Normal
          ...
12311    Normal
12312    Normal
12313    Normal
12314    Normal
12315    Normal
Name: Weather_conditions, Length: 12316, dtype: object

In [ ]:
# display multiple columns
df[["Age_band_of_driver","Accident_severity"]]

      Age_band_of_driver Accident_severity
0                  18-30     Slight Injury
1                  31-50     Slight Injury
2                  18-30    Serious Injury
3                  18-30     Slight Injury
4                  18-30     Slight Injury
...                  ...               ...
12311              31-50     Slight Injury
12312            Unknown     Slight Injury
12313            Over 51    Serious Injury
12314              18-30     Slight Injury
12315              18-30     Slight Injury

[12316 rows x 2 columns]

In [ ]:
#Filtering Condition
df[df["Weather_conditions"]=="Raining"]

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
15,22:45:00,Monday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,No distancing,Serious Injury
16,22:45:00,Monday,18-30,Male,Junior high school,Owner,5-10yr,Public (13?45 seats),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Moving Backward,Slight Injury
17,22:45:00,Monday,18-30,Male,Elementary school,Employee,2-5yr,Public (13?45 seats),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
18,22:45:00,Monday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,Above 10yr,...,Moving Backward,na,na,na,na,Unemployed,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
58,12:39:00,Tuesday,18-30,Unknown,Junior high school,Employee,Above 10yr,Automobile,Governmental,Above 10yr,...,Going straight,na,na,na,na,Employee,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12296,15:31:00,Monday,Over 51,Male,Junior high school,Employee,2-5yr,Automobile,Owner,2-5yrs,...,Going straight,Passenger,Male,5,2,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12297,12:30:00,Thursday,18-30,Male,Junior high school,Employee,5-10yr,Lorry (41?100Q),Owner,1-2yr,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving carelessly,Slight Injury
12298,18:45:00,Wednesday,18-30,Male,Junior high school,Employee,Above 10yr,Special vehicle,Owner,1-2yr,...,Going straight,Driver or rider,Male,18-30,3,Self-employed,Normal,Not a Pedestrian,No distancing,Slight Injury
12299,18:45:00,Wednesday,31-50,Male,Elementary school,Employee,2-5yr,Lorry (41?100Q),Owner,1-2yr,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
12302,17:25:00,Friday,31-50,Male,Junior high school,Employee,5-10yr,Automobile,Owner,1-2yr,...,Other,na,na,na,na,Self-employed,Normal,Not a Pedestrian,Moving Backward,Serious Injury

In [ ]:
# duplicates
df.duplicated().sum()

0

In [ ]:
# null values
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                    0
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality              3198
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                 0
Accident_severity                 0
dtype: int64

In [ ]:
# Simple Mode Imputation
# Education Level
df['Educational_level']=df['Educational_level'].fillna(df['Educational_level'].mode()[0])

In [ ]:
df['Educational_level'].isnull().sum()

0

In [ ]:
# Vehicle driver relation
df['Vehicle_driver_relation'] = df['Vehicle_driver_relation'].fillna(df['Vehicle_driver_relation'].mode()[0])

In [ ]:
df['Vehicle_driver_relation'].isnull().sum()

0

In [ ]:
# Rule Based If else(loc[])
# Owner of vehicle
# if driver relation is Owner
df.loc[
    (df['Owner_of_vehicle'].isnull()) &
    (df['Vehicle_driver_relation'] == 'Owner'),
    'Owner_of_vehicle'
] = 'Owner'

# if driver relation is Employee
df.loc[
    (df['Owner_of_vehicle'].isnull()) &
    (df['Vehicle_driver_relation'] == 'Employee'),
    'Owner_of_vehicle'
] = 'Company'

# if relation is Other
df.loc[
    (df['Owner_of_vehicle'].isnull()) &
    (df['Vehicle_driver_relation'] == 'Other'),
    'Owner_of_vehicle'
] = 'Other'

# remaining missing values
df['Owner_of_vehicle'] = df['Owner_of_vehicle'].fillna('Unknown')

In [ ]:
df['Owner_of_vehicle'].isnull().sum()

0

In [ ]:
# Group Based Mode Imputation
# Driving Experience
# fiiling missing driving experience based on age group
df['Driving_experience'] = df.groupby('Age_band_of_driver')['Driving_experience'] \
    .transform(lambda x: x.fillna(x.mode()[0]))

In [ ]:
df['Driving_experience'].isnull().sum()

0

In [ ]:
# Context_Based Imputation
# Road Surface Type
# fiiling based on weather condition
df['Road_surface_type'] = df.groupby('Weather_conditions')['Road_surface_type'] \
    .transform(lambda x: x.fillna(x.mode()[0]))

In [ ]:
df['Road_surface_type'].isnull().sum()

0

In [ ]:
# Mapping + fallback Conditional Filling
junction_map = {
    'Residential areas': 'Cross Road',
    'Office areas': 'T-Junction',
    ' Industrial areas': 'Roundabout',
    '  Market areas': 'Y-Junction',
    ' Church areas': 'T-Junction',
    ' Hospital areas': 'T-Junction',
    'School areas': 'Cross Road',
    'Rural village areas': 'No junction',
    ' Outside rural areas': 'No junction',
    'Recreational areas': 'Roundabout',
    '  Recreational areas': 'Roundabout',
    'Other': 'Unknown',
    'Unknown': 'Unknown',
    'Rural village areasOffice areas': 'T-Junction'
}

# Step 1: Fill using mapping
df['Types_of_Junction'] = df['Types_of_Junction'].fillna(
    df['Area_accident_occured'].map(junction_map)
)

# Step 2: Fill rows where Area_accident_occured itself is missing
df.loc[
    df['Types_of_Junction'].isnull(),
    'Types_of_Junction'
] = 'Unknown'

In [ ]:
df['Types_of_Junction'].isnull().sum()

0

In [ ]:
# Custom Function with apply()
# vehicle movement
def fill_vehicle_movement(row):
    if pd.isnull(row['Vehicle_movement']):
        if row['Type_of_collision'] == 'Collision with vehicles':
            return 'Moving Forward'
        elif row['Type_of_collision'] == 'Collision with pedestrians':
            return 'Going Straight'
        else:
            return 'Unknown'
    return row['Vehicle_movement']
#apply function
df['Vehicle_movement'] = df.apply(fill_vehicle_movement, axis=1)

In [ ]:
df['Vehicle_movement'].isnull().sum()

0

In [ ]:
# Creating Unknown category
#defect of vehicle
df['Defect_of_vehicle']=df['Defect_of_vehicle'].fillna('Unkown')

In [ ]:
df['Defect_of_vehicle'].isnull().sum()

0

In [ ]:
# Descriptive Unknown category
# Work of casuality
df['Work_of_casuality']=df['Work_of_casuality'].fillna('Occupation not recorded')

In [ ]:
df['Work_of_casuality'].isnull().sum()

0

In [ ]:
# Health Safe Unkown Replacement
# fitness of casuality
df['Fitness_of_casuality']=df['Fitness_of_casuality'].fillna('Unkown fitness status')

In [ ]:
df['Fitness_of_casuality'].isnull().sum()

0

In [ ]:
# Remaining Low-Missing Columns Using Mode
remaining_mode_cols = [
    'Type_of_vehicle',
    'Service_year_of_vehicle',
    'Area_accident_occured',
    'Lanes_or_Medians',
    'Road_allignment',
    'Type_of_collision'
]
for col in remaining_mode_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df[remaining_mode_cols].isnull().sum()

Type_of_vehicle            0
Service_year_of_vehicle    0
Area_accident_occured      0
Lanes_or_Medians           0
Road_allignment            0
Type_of_collision          0
dtype: int64

In [ ]:
# Final missing values after cleaning
df.isnull().sum()

Time                           0
Day_of_week                    0
Age_band_of_driver             0
Sex_of_driver                  0
Educational_level              0
Vehicle_driver_relation        0
Driving_experience             0
Type_of_vehicle                0
Owner_of_vehicle               0
Service_year_of_vehicle        0
Defect_of_vehicle              0
Area_accident_occured          0
Lanes_or_Medians               0
Road_allignment                0
Types_of_Junction              0
Road_surface_type              0
Road_surface_conditions        0
Light_conditions               0
Weather_conditions             0
Type_of_collision              0
Number_of_vehicles_involved    0
Number_of_casualties           0
Vehicle_movement               0
Casualty_class                 0
Sex_of_casualty                0
Age_band_of_casualty           0
Casualty_severity              0
Work_of_casuality              0
Fitness_of_casuality           0
Pedestrian_movement            0
Cause_of_accident              0
Accident_severity              0
dtype: int64

## Milestone 2

In [ ]:
## handling data types

In [ ]:
# check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            12316 non-null  object
 5   Vehicle_driver_relation      12316 non-null  object
 6   Driving_experience           12316 non-null  object
 7   Type_of_vehicle              12316 non-null  object
 8   Owner_of_vehicle             12316 non-null  object
 9   Service_year_of_vehicle      12316 non-null  object
 10  Defect_of_vehicle            12316 non-null  object
 11  Area_accident_occured        12316 non-null  object
 12  Lanes_or_Medians             12316 non-null  object
 13  Road_allignment              12316 non-null  object
 14  Types_of_Junction            12316 non-null  object
 15  Road_surface_type            12316 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12316 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12316 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            12316 non-null  object
 28  Fitness_of_casuality         12316 non-null  object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

In [ ]:
# Converting time column to datetime
df['Time'] = pd.to_datetime(
    df['Time'].astype(str).str.strip(),
    format='%H:%M:%S',
    errors='coerce'
)

In [ ]:
#Convert remaining object columns to category
cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].astype('category')

In [ ]:
#verify
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  datetime64[ns]
 1   Day_of_week                  12316 non-null  category
 2   Age_band_of_driver           12316 non-null  category
 3   Sex_of_driver                12316 non-null  category
 4   Educational_level            12316 non-null  category
 5   Vehicle_driver_relation      12316 non-null  category
 6   Driving_experience           12316 non-null  category
 7   Type_of_vehicle              12316 non-null  category
 8   Owner_of_vehicle             12316 non-null  category
 9   Service_year_of_vehicle      12316 non-null  category
 10  Defect_of_vehicle            12316 non-null  category
 11  Area_accident_occured        12316 non-null  category
 12  Lanes_or_Medians             12316 non-null  category
 13  Road_allignment              12316 non-null  category
 14  Types_of_Junction            12316 non-null  category
 15  Road_surface_type            12316 non-null  category
 16  Road_surface_conditions      12316 non-null  category
 17  Light_conditions             12316 non-null  category
 18  Weather_conditions           12316 non-null  category
 19  Type_of_collision            12316 non-null  category
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12316 non-null  category
 23  Casualty_class               12316 non-null  category
 24  Sex_of_casualty              12316 non-null  category
 25  Age_band_of_casualty         12316 non-null  category
 26  Casualty_severity            12316 non-null  category
 27  Work_of_casuality            12316 non-null  category
 28  Fitness_of_casuality         12316 non-null  category
 29  Pedestrian_movement          12316 non-null  category
 30  Cause_of_accident            12316 non-null  category
 31  Accident_severity            12316 non-null  category
dtypes: category(29), datetime64[ns](1), int64(2)
memory usage: 646.7 KB

In [ ]:
# =====================================================
# OUTLIER DETECTION
# =====================================================

num_cols = ['Number_of_vehicles_involved', 'Number_of_casualties']
# Dictionary to store IQR limits
limits = {}
print("Outliers Before Handling")
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
# Store limits for later verification
    limits[col] = (lower, upper)
# Count outliers
    outliers = ((df[col] < lower) | (df[col] > upper)).sum()
    print(f"{col}: {outliers} outliers")

Outliers Before Handling
Number_of_vehicles_involved: 3976 outliers
Number_of_casualties: 720 outliers

In [ ]:
# OUTLIER HANDLING USING IQR CAPPING
for col in num_cols:
    lower, upper = limits[col]
    # Cap extreme values
    df[col] = df[col].clip(lower, upper)
print("Outlier handling completed")

Outlier handling completed

In [ ]:
# OUTLIER VERIFICATION
print("\nOutliers After Handling")
for col in num_cols:
    lower, upper = limits[col]
    remaining = ((df[col] < lower) | (df[col] > upper)).sum()
    print(f"{col}: {remaining} outliers remaining")

Outliers After Handling
Number_of_vehicles_involved: 0 outliers remaining
Number_of_casualties: 0 outliers remaining

In [ ]:
# FEATURE ENGINEERING
# 1. Extract accident hour from Time column
df['Accident_Hour'] = df['Time'].dt.hour

# 2. Create time period feature
def get_time_period(hour):
    if pd.isna(hour):
        return 'Unknown'
    elif 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

df['Time_Period'] = df['Accident_Hour'].apply(get_time_period)

In [ ]:
# 3. Create weather risk indicator
df['High_Risk_Weather'] = np.where(
    df['Weather_conditions'].isin(['Raining', 'Fog or mist', 'Snow']),
    1,
    0
)

In [ ]:
# 4. Categorize number of vehicles involved
def vehicle_category(v):
    if v <= 1:
        return 'Low'
    elif v <= 3:
        return 'Medium'
    elif v <= 5:
        return 'High'
    else:
        return 'Very High'

df['Vehicles_Category'] = df['Number_of_vehicles_involved'].apply(vehicle_category)

In [ ]:
# 5. Categorize number of casualties
def casualty_category(c):
    if c == 0:
        return 'No Casualty'
    elif c <= 2:
        return 'Low'
    elif c <= 5:
        return 'Medium'
    else:
        return 'High'

df['Casualties_Category'] = df['Number_of_casualties'].apply(casualty_category)

In [ ]:
# Check new features
df[['Accident_Hour',
    'Time_Period',
    'High_Risk_Weather',
    'Vehicles_Category',
    'Casualties_Category']].head()

,Accident_Hour,Time_Period,High_Risk_Weather,Vehicles_Category,Casualties_Category
0,17,Evening,0,Medium,Low
1,17,Evening,0,Medium,Low
2,17,Evening,0,Medium,Low
3,1,Night,0,Medium,Low
4,1,Night,0,Medium,Low

In [ ]:
# FEATURE SELECTION
# Drop less useful columns
drop_cols = [
    'Time',                    # replaced by Accident_Hour
    'Pedestrian_movement',
    'Work_of_casuality',
    'Fitness_of_casuality'
]
# Create final selected dataset
df_selected = df.drop(columns=drop_cols)

In [ ]:
# Check final shape and columns
print("Original Shape:", df.shape)
print("Final Shape:", df_selected.shape)

Original Shape: (12316, 37)
Final Shape: (12316, 33)

In [ ]:
print("\\nFinal Selected Columns:")
print(df_selected.columns.tolist())

\nFinal Selected Columns:
['Day_of_week', 'Age_band_of_driver', 'Sex_of_driver', 'Educational_level', 'Vehicle_driver_relation', 'Driving_experience', 'Type_of_vehicle', 'Owner_of_vehicle', 'Service_year_of_vehicle', 'Defect_of_vehicle', 'Area_accident_occured', 'Lanes_or_Medians', 'Road_allignment', 'Types_of_Junction', 'Road_surface_type', 'Road_surface_conditions', 'Light_conditions', 'Weather_conditions', 'Type_of_collision', 'Number_of_vehicles_involved', 'Number_of_casualties', 'Vehicle_movement', 'Casualty_class', 'Sex_of_casualty', 'Age_band_of_casualty', 'Casualty_severity', 'Cause_of_accident', 'Accident_severity', 'Accident_Hour', 'Time_Period', 'High_Risk_Weather', 'Vehicles_Category', 'Casualties_Category']

In [ ]:
# =====================================================
# FINAL DATASET VALIDATION
# =====================================================

print("Final Missing Values:", df_selected.isnull().sum().sum())
print("Final Shape:", df_selected.shape)
print("\\nData Types Summary:")
print(df_selected.dtypes.value_counts())

Final Missing Values: 0
Final Shape: (12316, 33)
\nData Types Summary:
object      3
int32       2
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
float64     1
int64       1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
category    1
Name: count, dtype: int64